server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
#    upload-service:
#      path: /upload/**
#      serviceId: upload-service
#      strip-prefix: false
  host:
    socket-timeout-millis: 12000
    connect-timeout-millis: 12000
  ignored-services:
    - upload-service # 忽略upload-service服务 这种前面加  -  的是集合语法，可以配置多个



#     添加ribbon的超时时间设置
#    ribbon:
#      ReadTimeout: 30000
#      ConnectTimeout: 30000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeout-in-milliseconds: 3000





